### ISSUE TITLE
Possibility to adjust font size or term column?

### ISSUE THREAD

**Issue by abruegger** [cran/arsenal#6]
I just started using the arsenal package and am very happy with it!

One issue that I cannot solve is that the columns containing the stats in a `tableby` summary table are too narrow for their content (see screenshot). I was wondering if there's an option to do either of the following to make the table prettier:

- Make the term column (column 1) narrower (without deleting words in the question)
- Use a fix minimal width for columns 2-7
- Decrease the font size
- Change the digits in `range` (Wertebereich in German) to none

I would very much appreciate some tips as how to make this table more presentable.

![Screenshot 2020-04-21 at 06 18 54](https://user-images.githubusercontent.com/31000762/79825256-db8dea80-8398-11ea-8dda-0d75b9d889e3.png)

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!
