### ISSUE TITLE
footnote in tableby table

### ISSUE THREAD

**Issue by hulloa27** [cran/arsenal#8]
Hello,

Is it possible to put a footnote (not of statistical tests, but one where we can specify in writing (e.g. "This data only includes blahblah")) for tableby tables? 

Thank you!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by hulloa27** [comment]
Thank you!
